export const TIKI_KEYWORDS = [
    "travel planning",
    "trip organization",
    "timeline management",
    "budget tracking",
    "expense management",
    "travel itinerary",
    "vacation planner",
    "adventure planner",
    "trip scheduler",
    "trip itinerary builder",
    "relocation planner",
    "family travel planning",
    "travel budgeting",
    "expense forecasting",
    "itinerary calendar",
    "event reminders",
    "interactive timeline",
    "packing lists",
    "travel checklist",
    "trip organizer app",
    "holiday planner",
    "vacation budgeting tool",
    "travel cost analysis",
    "multi-stop trip planning",
    "travel route planner",
    "smart reminders",
    "travel notifications",
    "journey manager",
    "destination exploration",
    "activity scheduling",
    "travel expense calculator",
    "budget analytics",
    "expense insights",
    "cost forecasting",
    "progress tracking",
    "document storage",
    "trip preparation",
    "travel tools",
    "drag & drop interface",
    "travel route optimization",
    "online travel planner",
    "trip collaboration",
    "group travel management",
    "shared itineraries",
    "traveler profiles",
    "custom checklists",
    "checklist templates",
    "travel resources",
    "adventure checklist",
    "flight planning",
    "hotel reservations",
    "car rental organization",
    "transportation management",
    "travel insurance tracking",
    "travel date scheduler",
    "trip countdown",
    "holiday budget planner",
    "travel cost planner",
    "travel financial planner",
    "trip progress updates",
    "road trip organizer",
    "travel itinerary templates",
    "multi-destination travel",
    "trip planning timeline",
    "trip budgeting software",
    "vacation itinerary tool",
    "globetrotting organizer",
    "travel agenda",
    "trip expense ledger",
    "travel expense reporting",
    "travel notifications app",
    "flight deals tracking",
    "accommodation management",
    "travel events calendar",
    "trip cost breakdown",
    "travel itinerary calendar",
    "destination research",
    "travel suggestions",
    "travel scheduling",
    "tiki tours",
    "guided trips",
    "customized vacation planning",
    "relocation budgeting",
    "move planning",
    "travel route mapping",
    "location scouting",
    "travel event management",
    "travel day planner",
    "family trip app",
    "solo traveler planning",
    "couples travel organizer",
    "group vacation manager",
    "business travel management",
    "corporate trip planner",
    "employee travel budgeting",
    "event travel scheduling",
    "trip cost aggregator",
    "real-time expense tracking",
    "mobile travel planner",
    "remote travel planning",
    "interactive travel timeline",
    "day-by-day itinerary",
    "lodging comparison",
    "trip timeline visualization",
    "travel calendar integration",
    "digital travel diary",
    "trip memory tracker",
    "photo location logging",
    "reimbursement management",
    "travel goal setting",
    "travel budgeting goals",
    "holiday timeline",
    "trip route optimization",
    "tour planning software",
    "travel time estimator",
    "trip reminders app",
    "smart budgeting alerts",
    "trip cost savings",
    "travel plan automation",
    "itinerary share links",
    "expense sharing",
    "travel group collaboration",
    "community travel tips",
    "destination ideas",
    "country-specific checklists",
    "travel bullet journal",
    "time zone conversion",
    "currency conversion",
    "travel expense categories",
    "booking reference management",
    "trip invitation links",
    "interactive travel board",
    "map integrations",
    "location-based reminders",
    "traveler notifications",
    "passport and visa reminders",
    "travel immunization checklist",
    "health documents storage",
    "vaccination tracking",
    "activity boards",
    "day planner for travel",
    "vacation budget summary",
    "trip receipts storage",
    "travel expense sharing",
    "group cost splitting",
    "travel itinerary collaboration",
    "events and tours aggregator",
    "travel goal tracker",
    "trip tasks and deadlines",
    "travel activity manager",
    "trip timeline reminders",
    "automated travel reminders",
    "travel booking references",
    "travel resource library",
    "travel packing guides",
    "adventure budget manager",
    "relocation expense management",
    "international trip planning",
    "worldwide travel planner",
    "global travel budgeting",
    "time-based itinerary",
    "travel expense logs",
    "flight check-ins reminders",
    "hotel checklists",
    "rental car tracking",
    "trip mileage logs",
    "food budget management",
    "meal planning for travel",
    "overnight stay planning",
    "long-term travel scheduling",
    "digital travel wallet",
    "flight seat selection tracking",
    "tourist attraction manager",
    "local activity suggestions",
    "itinerary timeline for families",
    "interactive budget chart",
    "cost allocation for trips",
    "shared expense calculator",
    "travel banking integration",
    "travel budgeting goals app",
    "trip deposit tracking",
    "destination fact sheets",
    "tour booking manager",
    "adventure itinerary generator",
    "destination bucket list",
    "travel reward tracking",
    "vacation payoff calculator",
    "companion travel planning",
    "multiple currency management",
    "upcoming trip alerts",
    "trip countdown reminders",
    "landmark mapping",
    "offline travel lists",
    "adventure trip framework",
    "camping trip planner",
    "RV travel scheduling",
    "cruise trip scheduling",
    "frequent flyer miles tracker",
    "multi-country itinerary",
    "border crossing documentation",
    "visa expiry alerts",
    "transportation aggregator",
    "city pass management",
    "multi-activity travel planning",
    "trip highlights compilation",
    "trip reflection tools",
    "car share coordination",
    "outdoor adventure planning",
    "hiking trip organization",
    "destination wedding planner",
    "honeymoon itinerary",
    "travel content aggregator",
    "shared adventure logs",
    "group travel communication",
    "travel forum integration",
    "travel photos and notes",
    "digital travel scrapbook",
    "timeline notifications",
    "seasonal trip planning",
    "weather integration",
    "travel insurance aggregator",
    "travel tips library",
    "travel safety checklists",
    "emergency contact storage",
    "family itinerary syncing",
    "cost analysis dashboard",
    "trip reservation aggregator",
    "one-stop travel planner",
    "personal travel assistant",
    "travel document generator",
    "travel route overview",
    "trip summary report",
    "cost distribution",
    "group cost settlement",
    "travel micro-tasks",
    "trip advisories",
    "relocation budgeting tool",
    "multi-step itinerary builder",
    "flight aggregator",
    "hotel aggregator",
    "cost-saving insights",
    "budget optimization",
    "itinerary cost estimator",
    "quick travel notes",
    "day-by-day breakdown",
    "smart packing lists",
    "trip analytics",
    "long-term trip budgeting",
    "multi-currency ledger",
    "vacation breakdown tool",
    "plan relocations easily",
    "adventure logbook",
    "travel timeline sync",
    "integrated map routing",
    "travel route expansions",
    "journey planning system",
    "vacation readiness checks",
    "customizable budget categories",
    "Oceania travel planning",
    "Pacific Islands itinerary",
    "Australia tourism board",
    "New Zealand travel agencies",
    "Maori cultural experiences",
    "Aussie holiday planning",
    "Pacific cultural tours",
    "Aboriginal heritage sites",
    "Sydney city adventures",
    "Great Barrier Reef tours",
    "Polynesian cultural tours",
    "Fiji vacation packages",
    "Tonga travel budgeting",
    "Samoa travel checklists",
    "Vanuatu expedition planning",
    "Papua New Guinea trip management",
    "Torres Strait Islands travel",
    "Pacific cruising",
    "Kiwi traveler budgeting",
    "New Zealand road trip",
    "Australian outback itineraries",
    "Trans-Tasman tours",
    "Oceania tourism industry",
    "hospitality management software",
    "accommodation booking solutions",
    "travel agency collaboration",
    "tour operators platform",
    "event tourism planning",
    "destinations marketing",
    "resort booking coordination",
    "adventure tourism in Oceania",
    "eco-tourism in the Pacific",
    "backpacking routes in Australia",
    "travel insurance integration",
    "cruise line aggregator",
    "student travel in NZ",
    "remote worker travel planning",
    "digital nomad itineraries",
    "island hopping in the Pacific",
    "gap year adventures",
    "work and travel programs",
    "international tourism boards",
    "flight aggregator for Oceania",
    "hotel aggregator in Australasia",
    "Sydney Opera House tours",
  "Auckland city excursions",
  "Melbourne cultural festivals",
  "Queensland rainforest hikes",
  "Great Ocean Road adventures",
  "Uluru camping experiences",
  "Wellington harbor cruises",
  "Rotorua geothermal tours",
  "Cairns reef diving trips",
  "Gold Coast beach getaways",
  "Surfers Paradise nightlife",
  "Northland cultural heritage",
  "Tasmanian wilderness treks",
  "Lake Tekapo stargazing tours",
  "Aoraki Mount Cook expeditions",
  "New Caledonia island hopping",
  "Bora Bora luxury stays",
  "Tahiti black sand beaches",
  "Rarotonga lagoon cruises",
  "Cook Islands cultural immersion",
  "Kangaroo Island wildlife tours",
  "Barossa Valley wine tastings",
  "Marlborough wine region getaways",
  "Te Anau glowworm caves",
  "Wanaka adventure sports",
  "Queenstown ski packages",
  "Aussie bushwalking tours",
  "Outback station experiences",
  "Nelson Tasman scenic routes",
  "Hawke’s Bay gastronomic tours",
  "Adelaide Fringe Festival planning",
  "Bay of Islands maritime history",
  "Northwest Australia road trips",
  "Whitsunday sailing charters",
  "Fraser Island 4WD expeditions",
  "Hobart cultural city tours",
  "Launceston gorge cruises",
  "Milford Sound scenic flights",
  "Fiordland nature safaris",
  "Cradle Mountain guided hikes",
  "Hawkesbury River boat tours",
  "Broome camel rides",
  "Kimberley region explorations",
  "Broome to Darwin overland trips",
  "Gippsland Lakes kayaking",
  "Māori marae visits",
  "Waitangi Treaty Grounds trips",
  "Kaikōura whale watching",
  "Bay of Plenty orchard visits",
  "Thredbo ski resort planning",
  "Mt Ruapehu snow adventures",
  "Noosa surf escapes",
  "Byron Bay wellness retreats",
  "Waiheke Island vineyard hopping",
  "Weta Workshop film tours",
  "Australian coral reef conservation",
  "Ningaloo Reef snorkeling",
  "Magnetic Island wildlife",
  "Rotorua Māori cultural nights",
  "Napier Art Deco weekends",
  "Manly ferry passes",
  "Waiouru military museum visits",
  "Brisbane River dinner cruises",
  "Aoraki National Park treks",
  "Coral Sea helicopter tours",
  "Sydney Harbour Bridge climbs",
  "Perth city river cruises",
  "Walpole treetop walks",
  "Pinnacles Desert stargazing",
  "Taranaki surf and ski combos",
  "Southern Lights (Aurora Australis) viewing",
  "Wairarapa balloon festivals",
  "Auckland ferry pass aggregator",
  "Christchurch city rebuild tours",
  "Larnach Castle tours",
  "Punakaiki pancake rocks visits",
  "Margaret River cave explorations",
  "Katherine Gorge boat rides",
  "Nambung National Park trips",
  "Abel Tasman kayaking expeditions",
  "East Coast Tasmania scenic drive",
  "Freycinet National Park walks",
  "Apollo Bay beach stays",
  "Cape Reinga spiritual journeys",
  "Historic Russell town tours",
  "Kāpiti Island wildlife encounters",
  "Stewart Island star parties",
  "Timaru rose gardens visits",
  "Peppers Beach Club retreats",
  "Te Puia geyser experiences",
  "Ngāi Tahu tourism insights",
  "Moeraki Boulders sunrise tours",
  "Lake Wanaka photography workshops",
  "Sydney Mardi Gras festival planning",
  "Auckland Diwali festival outings",
  "Darwin art and culture festivals",
  "Palmerston North agritours",
  "Uluru Field of Light tours",
  "Warrnambool whale watching",
  "Torres Strait Islands festivals",
  "King Island golf trips",
  "Southern Highlands wine tours",
  "Tropical North Queensland safaris",
  "Waihi gold mining heritage",
  "Townsville Magnetic Island ferry passes",
  "Camel Safari Broome aggregator",
  "Beach resort aggregator for Oceania",
  "Kiwi Experience bus tours",
  "Indigenous-led travel experiences",
  "Pacific Islands volunteer programs",
  "Seasonal fruit picking trips",
  "Lord Howe Island eco-tours",
  "Cultural exchange homestays",
  "Artisan markets in Oceania",
  "Rangitoto Island summit walks",
  "Light rail integration for tourism",
  "Mt Taranaki scenic drives",
  "Wellington craft beer crawl",
  "Kai Kart gastronomic tours",
  "Wai-O-Tapu thermal wonderland visits",
  "Sydney coastal walks aggregator",
  "Auckland volcano explorations",
  "Nadi day tour aggregator",
  "Fiji honeymoon travel packages",
  "Resort booking aggregator for Fiji",
  "Solomon Islands cultural guide",
  "Vanuatu eco-lodge stays",
  "Samoa Upolu beach tours",
  "O’ahu to Auckland routes aggregator",
  "Polynesian canoe journeys",
  "Tongan whale swim experiences",
  "Niue self-drive exploration",
  "Norfolk Island colonial history tours",
  "Bespoke Oceania travel agencies",
  "Portal for Oz–NZ flight deals",
  "Pacific region flight pass aggregator",
  "Australasia hotel channel manager",
  "Local homestay aggregator in NZ",
  "Remote island adventure packages",
  "Cruise ship excursion aggregator",
  "Wildlife volunteering in Australia",
  "Wild kiwi encounter tours",
  "Regional tourism board partnerships",
  "Australian backpacker hostels aggregator",
  "Island-hopping cruise aggregator",
  "Oceania business travel synergy",
  "University study abroad aggregator",
  "Remote co-working travel programs",
  "Surf camp aggregator in Oceania",
  "Luxury lodge aggregator in NZ",
  "Historic gold rush trail tours",
  "Remote luxury glamping aggregator",
  "Northern Territory desert tours",
  "Tasman Sea ferry crossing aggregator",
  "Wairarapa wine and cheese pairing",
  "Mount Taranaki photography camps",
  "Aussie caravan holiday aggregator",
  "Bay of Islands sailboat charters",
  "Pacific cultural exchange platform",
  "TranzAlpine scenic railway aggregator",
  "Jucy campervan aggregator NZ",
  "Oceania orchard working holidays",
  "Cultural festival aggregator in the Pacific",
  "Auckland–Sydney trans-Tasman flights",
  "Event hosting aggregator for Australasia",
  "Aboriginal dreamtime experiences",
  "Oceania inbound travel marketing",
  "Tourism analytics dashboard for NZ/Aus",
  "Marine conservation tours in Oceania",
  "Beach cleanup volunteer aggregator",
  "Farmstay aggregator in New Zealand",
  "Wwoofing aggregator in Oceania",
  "Eco-luxury retreats aggregator",
  "Seasonal job aggregator for travelers",
  "NZ Great Walks booking aggregator",
  "Queensland theme park pass aggregator",
  "Trans-Tasman hiking pass aggregator",
  "Pacific region cultural festival aggregator",
  "Travel packages for Whakaari / White Island",
  "Wild Dolphin encounters in NZ",
  "Oceania cruise buffet aggregator",
  ];
  